### ISSUE TITLE
Add gcc-c++ to rebuild.sh

### ISSUE THREAD

**Issue by zanglang** [jcu-eresearch/shibboleth-fastcgi#2]
Running the commands in rebuild.sh on fresh Docker containers running CentOS 5-7 will be interrupted by the last step:

`[root@98c2094dfef5 /]# rpmbuild --rebuild shibboleth*.src.rpm --with fastcgi
Installing shibboleth-2.6.0-2.1.src.rpm
error: Failed build dependencies:
        gcc-c++ is needed by shibboleth-2.6.0-2.1.x86_64`

Might be useful to add that to the yum install -y step.

**Comment by davidjb** [comment]
Thanks for the report!  I'd missed this repo in my shift to rebuilding my scripts with using Docker instead of Vagrant so I've made some updates to the build script as well.  It now just installs the src rpm's dependencies so the only the manual installs needed (except for the basic tools, see the Dockerfile) are is `fcgi-devel` for FastCGI support (because I can't see where yum-builddep supports --with options) and the schema packages, because yum-builddep doesn't appear to support PreReq directives.

PRs fixing either of those two caveats is welcome, but the rebuild script is still a lot better with these changes.
